version: "3.9"

services:
  # Shared Redis for Microservice Communication
  redis:
    image: redis:alpine
    container_name: sdlc_redis
    ports:
      - "6379:6379"
    networks:
      - sdlc_network

  # Database for User Service
  user_service_db:
    image: postgres:18
    restart: always
    container_name: user_service_db
    environment:
      POSTGRES_USER: ${USER_SERVICE_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD:-password}
      POSTGRES_DB: user_service_db
    ports:
      - "5433:5432"
    volumes:
      - user_service_db_data:/var/lib/postgresql/data
    networks:
      - sdlc_network

networks:
  sdlc_network:
    driver: bridge

volumes:
  user_service_db_data:
